# Glenn Tech 블로그 설정

# 테마 설정
theme: jekyll-theme-chirpy

# 언어 설정
lang: ko

# 시간대 설정
timezone: Asia/Seoul

# 사이트 기본 정보
title: Glenn Tech
tagline: 기술 블로그
description: >-
  개발하면서 배운 것들을 정리하고 공유하는 기술 블로그입니다.

# 사이트 URL (GitHub Pages)
url: "https://g1ennk.github.io"

# GitHub 정보
github:
  username: g1ennk

# 소셜 미디어
social:
  name: 김민석 (Minseok Kim)
  email: mskim.glenn@gmail.com
  links:
    - https://github.com/g1ennk

# 사이트 검증 (선택사항)
webmaster_verifications:
  google: # Google Search Console
  bing: # Bing Webmaster Tools

# 웹 분석 (선택사항)
analytics:
  google:
    id: # Google Analytics ID

# 페이지뷰 설정
pageviews:
  provider: # goatcounter 지원

# 테마 모드 (자동)
theme_mode: # light | dark | auto

# CDN 설정
cdn:

# 아바타 이미지
avatar:

# 소셜 미디어 미리보기 이미지
social_preview_image:

# 목차 표시
toc: true

# 댓글 시스템
comments:
  provider: # disqus | utterances | giscus

# PWA 설정
pwa:
  enabled: true
  cache:
    enabled: true

# 페이지네이션
paginate: 10

# 기본 URL
baseurl: ""

# 포스트 설정
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/

# 카테고리 및 태그 아카이브
jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
